import React, { useState } from 'react';
import { Icon } from './icons';

export default function SymptomAI() {
  const [query, setQuery] = useState('');
  const [messages, setMessages] = useState<{ role: 'user' | 'ai', content: React.ReactNode }[]>([
    {
      role: 'ai',
      content: "Hello! I am the Keppler Clinical Assistant. Describe the patient's symptoms or ask questions about their medical records, and I will analyze the information across the Document Vault. \n\n*Note: AI suggestions are for informational purposes and do not replace clinical judgment.*"
    }
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const sessionId = React.useRef("demo_session_" + Math.floor(Math.random() * 10000)).current;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    const userMsg = query;
    setQuery('');
    setMessages(prev => [...prev, { role: 'user', content: userMsg }]);
    setIsTyping(true);
    setError(null);

    try {
      const res = await fetch('http://localhost:8000/api/v1/assistant/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          message: userMsg
        })
      });

      if (!res.ok) {
        throw new Error(`API returned ${res.status}`);
      }

      const data = await res.json();
      
      setMessages(prev => [...prev, {
        role: 'ai',
        content: (
          <div className="space-y-4">
            <div className="text-[13.5px] leading-relaxed whitespace-pre-wrap">
               {data.content}
            </div>

            {data.citations && data.citations.length > 0 && (
              <div className="bg-white border border-[#DDE2EC] rounded-md overflow-hidden mt-3">
                <div className="bg-[#F8FAFC] border-b border-[#DDE2EC] px-3 py-1.5 text-[11.5px] font-semibold text-gray-800 flex items-center gap-1.5">
                  <Icon.Eye /> Sources
                </div>
                <ul className="divide-y divide-[#F1F5F9] text-[11.5px] bg-white">
                  {data.citations.map((cite: any, idx: number) => (
                    <li key={idx} className="px-3 py-2 text-gray-600">
                      <strong>{cite.document_name || 'Document'}</strong>: "{cite.text_snippet}"
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="bg-[#FFFBEB] border border-[#FEF08A] rounded-md p-3 text-[11.5px] text-[#B45309] flex gap-2 items-start mt-4">
              <div className="mt-0.5"><Icon.Alert /></div>
              <div><strong>AI Assistance Only:</strong> This information is generated by the local vLLM instance. It should not be treated as a verified clinical diagnosis. Please confirm with clinical examination.</div>
            </div>
          </div>
        )
      }]);
    } catch (err) {
      console.error(err);
      setError("Failed to connect to the Assistant API. Is the backend running on port 8000?");
      // Remove the optimistic user message if we fail? No, let's keep it and just show the error.
    } finally {
      setIsTyping(false);
    }
  };

  const clearChat = () => {
    setMessages([
       {
        role: 'ai',
        content: "Chat cleared. How can I help you today?"
      }
    ]);
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-[#F0F2F5]">
      <div className="bg-white border-b border-[#DDE2EC] px-6 py-4 flex items-center justify-between flex-shrink-0">
        <div>
          <h1 className="text-lg font-semibold text-gray-900">Clinical AI Assistant (RAG)</h1>
          <p className="text-[12.5px] text-[#64748B]">Conversational interface querying your locally ingested document vault.</p>
        </div>
        <div className="flex gap-2">
          <button onClick={clearChat} className="h-8 px-3 bg-white border border-[#DDE2EC] text-[#1B4FD8] text-[12px] font-medium rounded hover:bg-[#F8FAFC] transition-colors">
            Clear Chat
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-hidden flex flex-col max-w-4xl mx-auto w-full border-x border-[#DDE2EC] bg-white relative">
        {error && (
           <div className="absolute top-4 left-4 right-4 z-10 bg-[#FEF2F2] border border-[#FCA5A5] text-[#991B1B] px-4 py-3 rounded-lg flex items-center gap-3 shadow-sm">
             <Icon.Alert />
             <div className="text-[13px] font-medium">{error}</div>
             <button onClick={() => setError(null)} className="ml-auto text-[#991B1B] hover:underline text-[12px]">Dismiss</button>
          </div>
        )}

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {messages.map((msg, i) => (
            <div key={i} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
              <div className={`w-8 h-8 rounded flex items-center justify-center flex-shrink-0 text-white text-[12px] font-bold ${msg.role === 'user' ? 'bg-[#475569]' : 'bg-[#1B4FD8]'}`}>
                {msg.role === 'user' ? 'DR' : 'AI'}
              </div>
              <div className={`max-w-[80%] rounded-lg p-4 text-[13.5px] leading-relaxed ${
                msg.role === 'user' 
                  ? 'bg-[#1B4FD8] text-white rounded-tr-none' 
                  : 'bg-[#F8FAFC] border border-[#DDE2EC] text-gray-800 rounded-tl-none'
              }`}>
                {msg.content}
              </div>
            </div>
          ))}
          
          {isTyping && (
            <div className="flex gap-4">
              <div className="w-8 h-8 rounded flex items-center justify-center flex-shrink-0 text-white text-[12px] font-bold bg-[#1B4FD8]">AI</div>
              <div className="bg-[#F8FAFC] border border-[#DDE2EC] rounded-lg rounded-tl-none p-4 flex gap-1.5 items-center h-[52px]">
                <div className="w-2 h-2 bg-[#94A3B8] rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-2 h-2 bg-[#94A3B8] rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-2 h-2 bg-[#94A3B8] rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
              </div>
            </div>
          )}
        </div>

        <div className="p-4 border-t border-[#DDE2EC] bg-white">
          <form onSubmit={handleSubmit} className="relative">
            <input 
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder="Ask a clinical question about the patient records..."
              className="w-full h-12 bg-[#F8FAFC] border border-[#DDE2EC] rounded-lg pl-4 pr-12 text-[13.5px] text-gray-900 focus:outline-none focus:border-[#1B4FD8] focus:ring-1 focus:ring-[#1B4FD8]"
            />
            <button 
              type="submit"
              disabled={!query.trim() || isTyping}
              className="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 flex items-center justify-center bg-[#1B4FD8] hover:bg-[#1740B4] text-white rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="22" y1="2" x2="11" y2="13"></line>
                <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
              </svg>
            </button>
          </form>
          <div className="text-center mt-2 text-[10.5px] text-[#94A3B8]">
            Hosp AI operates on locally hosted vLLM models. No patient data is sent to external services.
          </div>
        </div>
      </div>
    </div>
  );
}
